global:
  scrape_interval: 30s # minst 30

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["0.0.0.0:9090"]
  
  - job_name: "react"
    scheme: https
    metrics_path: /dashboard
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["petterssonhomeserver.se"]
        labels:
          instance: react