services:
  # School project SONAR CUBE

  # SonarQube Database (PostgreSQL)
  sonarqube-db:
    image: postgres:15
    container_name: sonarqube-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "${POSTGRES_PORT:-9098}:5432"
    volumes:
      - ${PROJECT_ROOT}/sonarqube/postgres:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar -d sonar"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  # SonarQube
  sonarqube:
    cpus: 1.5
    image: sonarqube:9.9-community
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    restart: unless-stopped
    ports:
      - "${SONAR_PORT:-9099}:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ${PROJECT_ROOT}/sonarqube/data:/opt/sonarqube/data
      - ${PROJECT_ROOT}/sonarqube/extensions:/opt/sonarqube/extensions
      - ${PROJECT_ROOT}/sonarqube/logs:/opt/sonarqube/logs
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 60s